# syntax=docker/dockerfile:1.9
ARG PYTHON_VERSION=3.14
FROM plone/server-prod-config:uv-${PYTHON_VERSION}

ARG KC_VERSION

LABEL maintainer="kitconcept GmbH <gov@plone.org.br>" \
      org.label-schema.name="ghcr.io/kitconcept/core-prod" \
      org.label-schema.description="kitconcept $KC_VERSION production image with Python $PYTHON_VERSION" \
      org.label-schema.vendor="kitconcept GmbH"


# See <https://hynek.me/articles/docker-signals/>.
STOPSIGNAL SIGINT
