name: Code analysis checks
on: [push]
jobs:
  codeanalysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        python-version: [3.8]
    env:
      GIT_NAME: volto-slider-block
      NAMESPACE: '@kitconcept'
      GIT_USER: 'kitconcept'
      GIT_BRANCH: ${GITHUB_REF##*/}
    steps:
      - name: Main checkout
        uses: actions/checkout@v2

      # node setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # node install
      - name: Install dependencies
        run: yarn install

      - name: Install yo and @plone/generator-volto
        run: npm i -g yo @plone/generator-volto

      - name: Setup addon testing environment
        run: npx -p @plone/scripts addon clone https://github.com/${{env.GIT_USER}}/${{env.GIT_NAME}}.git --branch ${{env.GIT_BRANCH}}

      # ESlint
      - name: ESlint
        run: cd addon-testing-project && yarn && yarn lint

      # Stylelint
      - name: Stylelint
        run: cd addon-testing-project && yarn && yarn stylelint

      # Prettier
      - name: Prettier
        run: cd addon-testing-project && yarn && yarn prettier:ci
